name: Tmo Nightly Merge Main TmoMain

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.MERGE_KEY}}
      - run: |
          git config user.name nightly-merge
          git config user.email nightly-merge@github.com
          git config merge.ours.driver true
          echo "Current head hash for reverting if needed"
          git rev-parse HEAD
          git fetch
          git checkout main
          git checkout tmo-main
          git merge -X theirs --no-edit --allow-unrelated-histories main
          git push
